# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hearus
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

